name: 'Deploy Flask App to AWS Amplify'

on:
  push:
    branches:
      - master  # Change to your desired branch

jobs:
  deploy:
    name: Deploy Flask Static Site to AWS Amplify
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Set up virtual environment
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build static files
    - name: Build Static Files
      run: |
        source venv/bin/activate
        python freeze.py  # Adjust to your static site generator

    # Step 5: Deploy to Amplify
    - name: Deploy to AWS Amplify
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_command: publish
        amplify_env: dev
        source_dir: "build"  # Adjust to match the directory containing your static files
        distribution_dir: "dist"  # Change if needed
        build_command: "npm run build"  # Update if you have specific build steps
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
