name: 'Deploy Flask Static Site to AWS Amplify'

on:
  push:
    branches:
      - master  # Adjust to the branch you want to deploy from

jobs:
  deploy:
    name: Deploy Flask Static Site to AWS Amplify
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies and freeze Flask app
    - name: Install Dependencies and Build Static Site
      run: |
        echo "Creating virtual environment and installing dependencies"
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        echo "Freezing the Flask app"
        python freeze.py  # Generates static files into the 'build' directory

# Step 3: Deploy static site to Amplify Hosting using AWS CLI
    - name: Deploy to AWS Amplify
      run: |
        aws amplify start-job \
          --app-id d2a5heqc1vs1ae \
          --branch-name master \
          --job-type RELEASE \
          --source-directory build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
