name: Deploy Flask App to AWS Amplify

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies

      # Step 4: Freeze Flask app to static site (using Flask-Frozen)
      - name: Freeze Flask app
        run: |
          echo "Freezing the Flask app"
          python freeze.py   # This will generate the static site using Flask-Frozen

      # Step 5: Create a zip of the build directory (if needed)
      - name: Create zip of build directory
        run: |
          echo "Zipping build directory"
          zip -r myapp.zip ./build  # Adjust the path if necessary

      # Step 6: Set up Node.js (to address the ES module issue)
      - name: Set up Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Using an older Node.js version to avoid ES module issues

      # Step 7: Deploy to AWS Amplify
      - name: Deploy to AWS Amplify
        uses: luisgreen/amplify_deployment@main
        with:
          appId: 'd2a5heqc1vs1ae'  # Your Amplify App ID
          branchName: 'master'  # The branch you are deploying to (e.g., 'master')
          artifactPath: './myapp.zip'  # Path to the zip file containing the build
          region: 'us-west-2'  # The AWS region where your Amplify app is hosted
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets for AWS credentials
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
