name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        echo "Installing dependencies"
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Static Site
      run: |
        echo "Building static files"
        python freeze.py  # Generate the static files into the ./build directory

    - name: Zip Build Directory
      run: |
        echo "Creating zip of the build directory"
        zip -r build.zip ./build  # Zip the build directory

    - name: Deploy to AWS Amplify
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "Deploying to AWS Amplify"
        aws amplify start-deployment \
          --app-id d2a5heqc1vs1ae \
          --branch-name master \
          --source-url file://$(pwd)/build.zip  # Deploy using the zipped file
