name: 'Deploy Flask App to AWS Amplify'

on:
  push:
    branches:
      - master  # Change to your desired branch for deployment

jobs:
  deploy:
    name: Deploy Flask Static Site to AWS Amplify
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Create and activate a virtual environment
    - name: Set up Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    # Step 4: Build the static site
    - name: Build Static Site
      run: |
        source venv/bin/activate
        python freeze.py  # Replace with your build command

    # Step 5: Deploy static files to AWS Amplify
    - name: Deploy to AWS Amplify
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_command: publish
        amplify_env: dev
        amplify_app_id: d2a5heqc1vs1ae
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
